
import React from 'react';
import { User, Post, PostType, Comment, Conversation, DirectMessage, Community, Opportunity, Product, ProductCategory, ProductCondition, Review } from './types';

export const users: { [key: string]: User } = {
  sato: { 
    id: 'u1', 
    name: 'Kenji Sato', 
    handle: 'kenji_sato', 
    email: 'kenji.sato@example.com',
    phoneNumber: '+81 90-1234-5678',
    avatar: 'https://picsum.photos/seed/user1/100/100',
    coverImage: 'https://picsum.photos/seed/cover1/1200/400',
    bio: 'Product Manager in Tokyo, passionate about cross-border projects and fintech innovations. 日本語 & English.',
    jobTitle: 'Product Manager',
    location: 'Tokyo, Japan',
    tags: ['#Fintech', '#ProductManagement', '#AI'],
    followingCount: 150,
    followerCount: 2300,
    postCount: 98,
  },
  li: { 
    id: 'u2', 
    name: 'Li Wei', 
    handle: 'liwei_dev', 
    email: 'li.wei@example.com',
    phoneNumber: '+86 138-1234-5678',
    avatar: 'https://picsum.photos/seed/user2/100/100',
    coverImage: 'https://picsum.photos/seed/cover2/1200/400',
    bio: 'AI Engineer building the future. Focused on NLP and computer vision. Open to collaborations. 中文 & English.',
    jobTitle: 'AI Engineer',
    location: 'Shanghai, China',
    tags: ['#AI', '#Developer', '#OpenSource', '#NLP'],
    followingCount: 88,
    followerCount: 5400,
    postCount: 42,
  },
  emily: { 
    id: 'u3', 
    name: 'Emily Carter', 
    handle: 'emily_c', 
    email: 'emily.carter@example.com',
    phoneNumber: '+1 415-555-0101',
    avatar: 'https://picsum.photos/seed/user3/100/100',
    coverImage: 'https://picsum.photos/seed/cover3/1200/400',
    bio: 'Venture Capitalist connecting East and West. Always looking for the next big thing in tech.',
    jobTitle: 'Venture Capitalist',
    location: 'San Francisco, USA',
    tags: ['#VC', '#Startups', '#Investing'],
    followingCount: 500,
    followerCount: 12000,
    postCount: 123,
  },
  chen: { 
    id: 'u4', 
    name: 'Chen Yue', 
    handle: 'chenyue_art', 
    email: 'chen.yue@example.com',
    phoneNumber: '+86 139-8765-4321',
    avatar: 'https://picsum.photos/seed/user4/100/100',
    coverImage: 'https://picsum.photos/seed/cover4/1200/400',
    bio: 'Digital Artist & Illustrator. Creating worlds with pixels and code. Commissions are open.',
    jobTitle: 'Digital Artist',
    location: 'Beijing, China',
    tags: ['#DigitalArt', '#Illustration', '#NFTs'],
    followingCount: 210,
    followerCount: 8900,
    postCount: 250,
  },
};

export const mockComments: Comment[] = [
    { id: 'c1', user: users.sato, text: '素晴らしい写真ですね！' },
    { id: 'c2', user: users.chen, text: 'This looks amazing! Where was this taken?' },
];

export const mockPosts: Post[] = [
  {
    id: 'p1',
    user: users.sato,
    content: 'Exploring the beautiful streets of Kyoto. The autumn colors are breathtaking this year. 🍁',
    type: PostType.Image,
    media: [
      { type: 'image', url: 'https://picsum.photos/seed/kyoto1/800/600' },
      { type: 'image', url: 'https://picsum.photos/seed/kyoto2/800/600' },
      { type: 'image', url: 'https://picsum.photos/seed/kyoto3/800/600' },
      { type: 'image', url: 'https://picsum.photos/seed/kyoto4/800/600' },
    ],
    likes: 1204,
    shares: 130,
    comments: mockComments,
    createdAt: '2h ago',
  },
  {
    id: 'p2',
    user: users.li,
    content: 'Just launched my new open-source project! It\'s a toolkit for building AI-powered applications. Check it out on GitHub. #AI #Developer #OpenSource',
    type: PostType.Text,
    likes: 856,
    shares: 210,
    comments: [{id: 'c3', user: users.emily, text: 'Congratulations! This is a huge achievement.'}],
    createdAt: '5h ago',
  },
    {
    id: 'p3',
    user: users.chen,
    content: 'Live from my studio! Painting a new piece, come hang out and chat. 🎨🖌️',
    type: PostType.Live,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/live1/800/450' }],
    likes: 3400,
    shares: 50,
    comments: [],
    viewers: 2800,
    createdAt: 'Now',
  },
  {
    id: 'p4',
    user: users.emily,
    content: 'A quick look at my recent trip to the coast. The sound of the waves is so calming.',
    type: PostType.Video,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/video1/800/450' }],
    likes: 932,
    shares: 88,
    comments: [],
    createdAt: '1d ago',
  },
  {
    id: 'p5',
    user: users.li,
    content: 'Just a couple of shots from my recent project photoshoot.',
    type: PostType.Image,
    media: [
      { type: 'image', url: 'https://picsum.photos/seed/project1/600/600' },
      { type: 'image', url: 'https://picsum.photos/seed/project2/600/600' },
    ],
    likes: 450,
    shares: 45,
    comments: [],
    createdAt: '2d ago',
  },
  {
    id: 'p6',
    user: users.sato,
    content: 'Another live session about financial markets in Asia. Join us!',
    type: PostType.Live,
    media: [{ type: 'image', url: 'https://picsum.photos/seed/live2/800/450' }],
    likes: 1200,
    shares: 15,
    comments: [],
    viewers: 950,
    createdAt: 'Now',
  },
  {
    id: 'p7',
    user: users.chen,
    content: 'The complete nine-panel digital art series I\'ve been working on. Each one tells a part of the story.',
    type: PostType.Image,
    media: [
      { type: 'image', url: 'https://picsum.photos/seed/art1/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art2/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art3/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art4/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art5/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art6/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art7/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art8/400/400' },
      { type: 'image', url: 'https://picsum.photos/seed/art9/400/400' },
    ],
    likes: 2500,
    shares: 300,
    comments: [],
    createdAt: '3d ago',
  },
];

const now = Date.now();
export const mockConversations: Conversation[] = [
    {
        id: 'conv1',
        participants: [users.li, users.sato],
        unreadCount: 2,
        messages: [
            { id: 'dm1-1', senderId: 'u1', text: 'Hey Li Wei, saw your new project. Looks amazing!', timestamp: now - 1000 * 60 * 60 * 2 },
            { id: 'dm1-2', senderId: 'u2', text: 'Thanks, Kenji! Appreciate you checking it out.', timestamp: now - 1000 * 60 * 60 * 1.5 },
            { id: 'dm1-3', senderId: 'u1', text: 'Seriously impressive work. We should catch up properly soon.', timestamp: now - 1000 * 60 * 5 },
            { id: 'dm1-4', senderId: 'u1', text: 'Let me know when you are free next week.', timestamp: now - 1000 * 60 * 4 },
        ]
    },
    {
        id: 'conv2',
        participants: [users.li, users.emily],
        messages: [
            { id: 'dm2-1', senderId: 'u3', text: 'That video from your trip was beautiful!', timestamp: now - 1000 * 60 * 60 * 24 * 2 },
            { id: 'dm2-2', senderId: 'u2', text: 'Thank you! It was a very relaxing place.', timestamp: now - 1000 * 60 * 60 * 24 * 2 + 10000 },
            { id: 'dm2-3', senderId: 'u3', text: 'Check out this photo I took!', timestamp: now - 1000 * 60 * 60 * 24 * 1, media: { type: 'image', url: 'https://picsum.photos/seed/chatimg1/400/300' } },
        ]
    },
    {
        id: 'conv3',
        participants: [users.li, users.chen],
        unreadCount: 1,
        messages: [
            { id: 'dm3-1', senderId: 'u4', text: 'Your art series is mind-blowing. The detail is incredible.', timestamp: now - 1000 * 60 * 30 },
        ]
    }
];


export const mockCommunities: Community[] = [
    {
        id: 'com1',
        name: '日中翻訳・通訳コミュニティ',
        description: 'プロと学習者が集まり、翻訳スキルやキャリアについて情報交換する場です。',
        bannerImage: 'https://picsum.photos/seed/comm1/600/200',
        memberCount: 12500,
        tags: ['#Translation', '#Localization', '#Language'],
        members: [users.sato, users.chen],
        latestPostPreview: { author: 'Kenji Sato', content: 'Just shared a list of useful tools for technical translation...' }
    },
    {
        id: 'com2',
        name: 'AI Developers in Asia',
        description: 'A group for AI engineers and researchers across Asia to share breakthroughs, projects, and collaborate.',
        bannerImage: 'https://picsum.photos/seed/comm2/600/200',
        memberCount: 8900,
        tags: ['#AI', '#MachineLearning', '#Tech', '#Developer'],
        members: [users.li, users.sato, users.emily],
        latestPostPreview: { author: 'Li Wei', content: 'Posted a new paper on cross-lingual NLP models. Looking for feedback!' }
    },
    {
        id: 'com3',
        name: '日本での就職・キャリア',
        description: '日本での就職を目指す外国籍人材のための情報交換コミュニティ。面接対策や企業文化について話しましょう。',
        bannerImage: 'https://picsum.photos/seed/comm3/600/200',
        memberCount: 23000,
        tags: ['#Career', '#Japan', '#JobSeekers'],
        members: [users.sato, users.emily],
        latestPostPreview: { author: 'Emily Carter', content: 'Webinar next week: How to negotiate your salary in a Japanese company.' }
    }
];

export const mockOpportunities: Opportunity[] = [
    {
        id: 'opp1',
        title: 'Bilingual Product Manager (JP/CN)',
        company: 'InnovateTech Tokyo',
        location: 'Tokyo, Japan',
        description: 'Seeking a product manager to lead our new cross-border fintech application targeted at the Chinese market.',
        type: 'Full-time',
        tags: ['#Fintech', '#ProductManagement', '#Bilingual', '#Japan'],
    },
    {
        id: 'opp2',
        title: 'Frontend Developer (React/Vue)',
        company: 'Byte Creative Shanghai',
        location: 'Shanghai, China (Remote OK)',
        description: 'Join our creative team to build stunning web experiences for global brands entering the Japanese market.',
        type: 'Contract',
        tags: ['#Frontend', '#React', '#RemoteWork', '#Developer'],
    },
    {
        id: 'opp3',
        title: 'Collaboration: AI Translation App',
        company: 'Li Wei (Personal Project)',
        location: 'Cross-border',
        description: 'Looking for a UI/UX designer with experience in Japanese and Chinese markets to collaborate on a new AI translation app.',
        type: 'Collaboration',
        tags: ['#AI', '#Design', '#Startup', '#Translation'],
    }
];

// E-commerce Mock Data
export const mockProducts: Product[] = [
    {
        id: 'prod1',
        title: '韩版ins风连衣裙 2024春款',
        description: '超美的韩版连衣裙，面料柔软舒适，显瘦显高，适合日常通勤和约会。只穿过一次，9成新。',
        price: 168,
        originalPrice: 299,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/dress1/600/800',
            'https://picsum.photos/seed/dress2/600/800',
            'https://picsum.photos/seed/dress3/600/800',
        ],
        seller: users.chen,
        category: ProductCategory.Fashion,
        condition: ProductCondition.LikeNew,
        stock: 1,
        sold: 0,
        rating: 4.8,
        reviewCount: 0,
        location: '北京市',
        tags: ['#连衣裙', '#韩版', '#春装', '#女装'],
        createdAt: '1h ago',
        isLiked: false,
    },
    {
        id: 'prod2',
        title: 'iPhone 15 Pro Max 256GB 黑色钛金属',
        description: '国行正品，自用一个月，几乎全新。配件齐全，保修至2025年10月。支持验货。',
        price: 7899,
        originalPrice: 9999,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/iphone1/600/800',
            'https://picsum.photos/seed/iphone2/600/800',
        ],
        seller: users.li,
        category: ProductCategory.Electronics,
        condition: ProductCondition.LikeNew,
        stock: 1,
        sold: 0,
        rating: 5.0,
        reviewCount: 12,
        location: '上海市',
        tags: ['#iPhone', '#苹果', '#手机', '#数码'],
        createdAt: '3h ago',
        isLiked: true,
    },
    {
        id: 'prod3',
        title: '日本直邮资生堂红腰子精华 50ml',
        description: '日本专柜购入，全新未拆封。红腰子精华，抗老修复，改善细纹。保质期到2026年。',
        price: 580,
        originalPrice: 780,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/shiseido1/600/800',
            'https://picsum.photos/seed/shiseido2/600/800',
        ],
        seller: users.sato,
        category: ProductCategory.Beauty,
        condition: ProductCondition.New,
        stock: 3,
        sold: 15,
        rating: 4.9,
        reviewCount: 28,
        location: '东京',
        tags: ['#美妆', '#护肤', '#日本代购', '#资生堂'],
        createdAt: '5h ago',
        isLiked: false,
    },
    {
        id: 'prod4',
        title: '北欧风格ins网红台灯',
        description: '简约现代设计，三档调光，护眼LED。装修剩下的，全新未使用。',
        price: 89,
        originalPrice: 159,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/lamp1/600/800',
        ],
        seller: users.chen,
        category: ProductCategory.Home,
        condition: ProductCondition.New,
        stock: 2,
        sold: 5,
        rating: 4.6,
        reviewCount: 8,
        location: '北京市',
        tags: ['#家居', '#台灯', '#北欧风', '#装饰'],
        createdAt: '1d ago',
        isLiked: false,
    },
    {
        id: 'prod5',
        title: '村上春树文集 全套12本',
        description: '经典收藏版，全新未拆封。包括《挪威的森林》《1Q84》等经典作品。',
        price: 299,
        originalPrice: 498,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/books1/600/800',
            'https://picsum.photos/seed/books2/600/800',
        ],
        seller: users.sato,
        category: ProductCategory.Books,
        condition: ProductCondition.New,
        stock: 5,
        sold: 23,
        rating: 4.9,
        reviewCount: 35,
        location: '东京',
        tags: ['#书籍', '#村上春树', '#文学', '#日本文学'],
        createdAt: '2d ago',
        isLiked: true,
    },
    {
        id: 'prod6',
        title: 'Nike Air Jordan 1 High OG 黑红配色',
        description: '经典款AJ1，US9.5码，8成新，鞋盒配件齐全。鞋况良好，无大瑕疵。',
        price: 1280,
        originalPrice: 1899,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/aj1/600/800',
            'https://picsum.photos/seed/aj2/600/800',
            'https://picsum.photos/seed/aj3/600/800',
        ],
        seller: users.li,
        category: ProductCategory.Fashion,
        condition: ProductCondition.Used,
        stock: 1,
        sold: 0,
        rating: 4.7,
        reviewCount: 0,
        location: '上海市',
        tags: ['#球鞋', '#AJ', '#Nike', '#运动'],
        createdAt: '2d ago',
        isLiked: false,
    },
    {
        id: 'prod7',
        title: 'Switch游戏卡带《塞尔达传说：王国之泪》',
        description: '自用游戏卡带，已通关。卡带无划痕，可正常使用。',
        price: 299,
        originalPrice: 429,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/zelda1/600/800',
        ],
        seller: users.chen,
        category: ProductCategory.Toys,
        condition: ProductCondition.Used,
        stock: 1,
        sold: 0,
        rating: 4.8,
        reviewCount: 0,
        location: '北京市',
        tags: ['#游戏', '#Switch', '#塞尔达', '#任天堂'],
        createdAt: '3d ago',
        isLiked: false,
    },
    {
        id: 'prod8',
        title: '手工陶瓷茶具套装',
        description: '景德镇手工制作，一壶四杯，釉色温润。适合送礼或自用。',
        price: 388,
        currency: '¥',
        images: [
            'https://picsum.photos/seed/tea1/600/800',
            'https://picsum.photos/seed/tea2/600/800',
        ],
        seller: users.chen,
        category: ProductCategory.Home,
        condition: ProductCondition.New,
        stock: 8,
        sold: 42,
        rating: 4.9,
        reviewCount: 56,
        location: '北京市',
        tags: ['#茶具', '#陶瓷', '#手工', '#景德镇'],
        createdAt: '1w ago',
        isLiked: true,
    },
];

export const mockReviews: Review[] = [
    {
        id: 'rev1',
        productId: 'prod2',
        user: users.chen,
        rating: 5,
        comment: '手机成色很好，和描述一致！卖家人很nice，支持验货。强烈推荐！',
        images: ['https://picsum.photos/seed/review1/400/300'],
        createdAt: '1d ago',
        likes: 12,
    },
    {
        id: 'rev2',
        productId: 'prod3',
        user: users.emily,
        rating: 5,
        comment: '正品！用了一周，皮肤状态明显改善。包装完好，发货很快。',
        createdAt: '3d ago',
        likes: 8,
    },
    {
        id: 'rev3',
        productId: 'prod3',
        user: users.li,
        rating: 4,
        comment: '好用，就是价格有点贵。不过是正品，值得购买。',
        createdAt: '1w ago',
        likes: 5,
    },
    {
        id: 'rev4',
        productId: 'prod5',
        user: users.chen,
        rating: 5,
        comment: '书的质量很好，装帧精美。村上春树迷必收！',
        createdAt: '2w ago',
        likes: 15,
    },
    {
        id: 'rev5',
        productId: 'prod8',
        user: users.sato,
        rating: 5,
        comment: '茶具非常精致，手工制作的质感很好。泡茶很有感觉。',
        images: ['https://picsum.photos/seed/review2/400/300'],
        createdAt: '3w ago',
        likes: 23,
    },
];